name: main-build

on:
  release:
    types: [created]

jobs:
  build:
    permissions: write-all
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: amyu/setup-android@v2
        if: runner.os == 'Linux'
        with:
          cache-disabled: false
          sdk-version: '34'
          build-tools-version: '34.0.0'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build APK
        run: ./gradlew :androidApp:assembleRelease
        if: runner.os == 'Linux'

      - name: Build App Bundle
        run: ./gradlew :androidApp:bundleRelease
        if: runner.os == 'Linux'

      - name: Build Desktop App
        run: ./gradlew :desktopApp:packageReleaseDistributionForCurrentOS

      - name: Build Web App
        run: |
          ./gradlew :webapp:jsBrowserProductionWebpack
          ./gradlew :webapp:jsBrowserProductionWebpack
        if: runner.os == 'Linux'

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: |
            androidApp/build/outputs/apk/release/*.apk
            androidApp/build/outputs/bundle/release/*.aab
            desktopApp/build/compose/binaries/main-release/*/*.*
            webApp/build/distributions/*

      - name: Upload APK, AAB, Desktop App and Web App to release
        if: ${{ github.event.release }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            androidApp/build/outputs/apk/release/*.apk
            androidApp/build/outputs/bundle/release/*.aab
            desktopApp/build/compose/binaries/main-release/*/*.*
            webApp/build/distributions/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}